/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerResult {
  'correctIndex' : bigint,
  'correct' : boolean,
  'bonusCoins' : Coins,
  'coinsAwarded' : Coins,
}
export type Coins = bigint;
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface LeaderboardEntry {
  'streak' : bigint,
  'username' : UserId,
  'rank' : bigint,
  'totalCoins' : Coins,
}
export interface LoginResult {
  'bonusCoins' : Coins,
  'isNewStreak' : boolean,
  'streakDay' : bigint,
  'profile' : UserProfilePublic,
}
export interface Question {
  'id' : QuestionId,
  'correctIndex' : bigint,
  'difficulty' : Difficulty,
  'text' : string,
  'category' : string,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export type UserId = string;
export interface UserProfilePublic {
  'streak' : bigint,
  'username' : UserId,
  'totalCoins' : Coins,
  'lastLoginDay' : bigint,
}
export interface _SERVICE {
  'awardQuizCoins' : ActorMethod<[UserId, Coins], undefined>,
  'checkAnswer' : ActorMethod<[QuestionId, bigint, bigint], AnswerResult>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getQuestions' : ActorMethod<[Difficulty], Array<Question>>,
  'loginOrRegister' : ActorMethod<[UserId], LoginResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];