/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Coins = IDL.Nat;
export const QuestionId = IDL.Nat;
export const AnswerResult = IDL.Record({
  'correctIndex' : IDL.Nat,
  'correct' : IDL.Bool,
  'bonusCoins' : Coins,
  'coinsAwarded' : Coins,
});
export const LeaderboardEntry = IDL.Record({
  'streak' : IDL.Nat,
  'username' : UserId,
  'rank' : IDL.Nat,
  'totalCoins' : Coins,
});
export const UserProfilePublic = IDL.Record({
  'streak' : IDL.Nat,
  'username' : UserId,
  'totalCoins' : Coins,
  'lastLoginDay' : IDL.Int,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'correctIndex' : IDL.Nat,
  'difficulty' : Difficulty,
  'text' : IDL.Text,
  'category' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const LoginResult = IDL.Record({
  'bonusCoins' : Coins,
  'isNewStreak' : IDL.Bool,
  'streakDay' : IDL.Nat,
  'profile' : UserProfilePublic,
});

export const idlService = IDL.Service({
  'awardQuizCoins' : IDL.Func([UserId, Coins], [], []),
  'checkAnswer' : IDL.Func(
      [QuestionId, IDL.Nat, IDL.Nat],
      [AnswerResult],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
  'getQuestions' : IDL.Func([Difficulty], [IDL.Vec(Question)], ['query']),
  'loginOrRegister' : IDL.Func([UserId], [LoginResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Coins = IDL.Nat;
  const QuestionId = IDL.Nat;
  const AnswerResult = IDL.Record({
    'correctIndex' : IDL.Nat,
    'correct' : IDL.Bool,
    'bonusCoins' : Coins,
    'coinsAwarded' : Coins,
  });
  const LeaderboardEntry = IDL.Record({
    'streak' : IDL.Nat,
    'username' : UserId,
    'rank' : IDL.Nat,
    'totalCoins' : Coins,
  });
  const UserProfilePublic = IDL.Record({
    'streak' : IDL.Nat,
    'username' : UserId,
    'totalCoins' : Coins,
    'lastLoginDay' : IDL.Int,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'correctIndex' : IDL.Nat,
    'difficulty' : Difficulty,
    'text' : IDL.Text,
    'category' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const LoginResult = IDL.Record({
    'bonusCoins' : Coins,
    'isNewStreak' : IDL.Bool,
    'streakDay' : IDL.Nat,
    'profile' : UserProfilePublic,
  });
  
  return IDL.Service({
    'awardQuizCoins' : IDL.Func([UserId, Coins], [], []),
    'checkAnswer' : IDL.Func(
        [QuestionId, IDL.Nat, IDL.Nat],
        [AnswerResult],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
    'getQuestions' : IDL.Func([Difficulty], [IDL.Vec(Question)], ['query']),
    'loginOrRegister' : IDL.Func([UserId], [LoginResult], []),
  });
};

export const init = ({ IDL }) => { return []; };